trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'trevette-api/trevette-api.csproj'
    
- task: DotNetCoreCLI@2
  inputs:  
    command: 'test'
    projects: 'trevette-api.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
